### ISSUE TITLE
Cache Gradle Dependencies

### ISSUE THREAD

**Issue by prbblrypier** [corese-stack/corese-core#111]
To optimize the build process and reduce the time spent on downloading dependencies during each build, you can leverage Gradle dependency caching. 

```
- name: Cache Gradle dependencies
  uses: actions/cache@v3
  with:
    path: ~/.gradle/caches
    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    restore-keys: |
      ${{ runner.os }}-gradle-

```
